### ISSUE TITLE
Ajouter la version OCaml

### ISSUE THREAD

**Issue by michipili** [TapTempo-Federation/TapTempo-Federation#10]
https://linuxfr.org/users/duga/journaux/portage-de-taptempo-en-ocaml

**Comment by gndl** [comment]
Le projet a été cloné dans l'organisation TapTempo-Federation. @michipili, y-a t'il autre chose à faire avant de pouvoir fermer la demande?

**Comment by michipili** [comment]
Non c'est bon! Merci! :)
