### ISSUE TITLE
Ajouter la version Ada

### ISSUE THREAD

**Issue by michipili** [TapTempo-Federation/TapTempo-Federation#16]
https://linuxfr.org/users/blackknight/journaux/portage-de-taptempo-en-ada

**Comment by FredPraca** [comment]
Cloned

**Comment by FredPraca** [comment]
Cloned # [adataptempo](https://github.com/Taptempo-Federation/adataptempo)

**Comment by michipili** [comment]
Super, merci! :)

**Comment by michipili** [comment]
Ceci dit le vrai nom utilise la ChameauCasse #26, peut-être qu'on pourrait changer le nom? Mais je ne veux pas épuiser dès le début tous les sujets de discussions possibles!

**Comment by FredPraca** [comment]
Tu as bien raison mais je suis ennuyé, il y a aussi les règles de codage du langage qui rentre en ligne de compte, déjà que j'ai pris quelques libertés... ;)

**Comment by michipili** [comment]
Bon ça fait un moment que j'ai fait le clone, c'est le moment de clore ce ticket. Merci! :)
