### ISSUE TITLE
Ajouter la version JavaScript

### ISSUE THREAD

**Issue by michipili** [TapTempo-Federation/TapTempo-Federation#2]
https://linuxfr.org/users/wawet76/journaux/portage-de-taptempo-en-javascript

**Comment by michipili** [comment]
https://github.com/TapTempo-Federation/TapTempo-javascript

J'ai fait comme ça, ça vous inspire quoi niveau attribution et licence?

**Comment by Wawet76** [comment]
> ça vous inspire quoi niveau attribution et licence?

Ça me convient.

**Comment by michipili** [comment]
Cool, merci!
