### ISSUE TITLE
Ajouter la version Chisel

### ISSUE THREAD

**Issue by Martoni** [TapTempo-Federation/TapTempo-Federation#29]
Je n'ai pas terminer le truc, mais j'ai ouvert un github pour faire une version «hardware» de TapTempo en utilisant chisel3:
https://github.com/Martoni/TapTempoChisel

**Comment by michipili** [comment]
Tu bluffes Martoni, tu bluffes.

**Comment by michipili** [comment]
C'est fait, merci! :)

https://github.com/TapTempo-Federation/TapTempo-chisel

**Comment by Martoni** [comment]
Il dit qu'il a plus d'genoux
