### ISSUE TITLE
Ajouter la version ABrainFuck

### ISSUE THREAD

**Issue by icefinger** [TapTempo-Federation/TapTempo-Federation#34]
Bien le bonjour.
Une milestone majeure a été franchie: ce n'est pas uniquement la technologie qui permet taptempo, taptempo a généré une nouvelle technologie: ABrainFuck.
Je propose d'ajouter son repo dans les repos de taptempo. Merci
https://github.com/icefinger/ABrainFuck (contient aussi une version de taptempo)

**Comment by michipili** [comment]
Bravo, merci à toi!
